stages:
  - install
  - build
  - deploy

image: node:alpine

cache:
  key: nodeModules
  paths:
    - node_modules

job_install:
  stage: install
  script:
    - npm uninstall node-sass
    - npm install node-sass --registry=http://registry.npm.taobao.org
    - npm install --force
    
job_build:
  stage: build
  script:
    - npm install
    
job_deploy:
  stage: deploy
  script:
    - npm install