stages:
  - install
  - build
  - deploy

cache:
  key: nodeModules
  paths:
    - node_modules
    - dist

job_install:
  stage: install
  tags:
    - cvtags
  only:
    refs:
        - dev
  script:
    - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - npm install --registry=http://registry.npm.taobao.org
    
job_build:
  stage: build
  tags:
    - cvtags
  only:
    - tags
  script:
    - npm run build

job_deploy:
  stage: deploy
  tags:
    - cvtags
  only:
    - /^dep-.*$/
  script:
    - sudo cp -rf ./dist/*  /var/www/html/
