stages:
  - install
  - build
  - deploy

image: node:alpine

cache:
  key: nodeModules
  paths:
    - node_modules

job_install:
  stage: install
  script:
    - yarn --registry=https://registry.npm.taobao.org && yarn
    
job_build:
  stage: build
  script:
    - npm install
    
job_deploy:
  stage: deploy
  script:
    - npm install