stages:
  - install
  - build
  - deploy

cache:
  key: nodeModules
  paths:
    - node_modules
    - dist

job_install:
  stage: install
  tags:
    - cvtags
  script:
    - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - npm install --registry=http://registry.npm.taobao.org
    
job_build:
  stage: build
  tags:
    - cvtags
  script:
    - npm build
  artifacts:
    paths:
        - dist
    expire_in: 2 hrs
    
job_deploy:
  stage: deploy
  tags:
    - cvtags
  script:
    - sudo cp -rf ./dist/*  /var/www/html/