stages:
  - install
  - build
  - deploy

cache:
  key: nodeModules
  paths:
    - node_modules

job_install:
  stage: install
  script:
    - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - npm install --registry=http://registry.npm.taobao.org
    
job_build:
  stage: build
  script:
    - npm install
    
job_deploy:
  stage: deploy
  script:
    - npm install